"""
Django settings for sfm project.

Generated by 'django-admin startproject' using Django 2.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4+(q7xcv(_-*1jsi^o&2_rky)oz)h8n+mi=*ea=&408j9%k^@r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # Third party
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'crispy_forms',

    # Local
    'users.apps.UsersConfig',
    'game.apps.GameConfig',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sfm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sfm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE'    : 'django.db.backends.postgresql',
        'NAME'      : 'postgres',
        'USER'      : 'postgres',
        'PASSWORD'  : 'postgres',
        'HOST'      : 'db',
        'PORT'      : 5432
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'


# Custom user
AUTH_USER_MODEL = 'users.CustomUser'

# Allauth (settings from https://django-allauth.readthedocs.io/en/latest/configuration.html)
LOGIN_REDIRECT_URL                      = 'router'
ACCOUNT_LOGOUT_REDIRECT_URL             = 'account_login'
ACCOUNT_AUTHENTICATION_METHOD           = 'email'
ACCOUNT_EMAIL_REQUIRED                  = True
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS  = 14
ACCOUNT_EMAIL_VERIFICATION              = 'mandatory'   # Login disallowed before email verification
ACCOUNT_EMAIL_SUBJECT_PREFIX            = '[SFM] '
ACCOUNT_LOGIN_ATTEMPTS_LIMIT            = 4
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT          = 600
ACCOUNT_PRESERVE_USERNAME_CASING        = False
ACCOUNT_SESSION_REMEMBER                = True
ACCOUNT_USERNAME_REQUIRED               = False


SITE_ID = 1

AUTHENTICATION_BACKENDS = {
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
}

# Email
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Thousand separators
USE_THOUSAND_SEPARATOR = True

# Django Crispy Forms
CRISPY_TEMPLATE_PACK = 'bootstrap4'

