# Generated by Django 2.2.10 on 2020-02-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200225_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='facilites',
            new_name='facilities',
        ),
    ]
