# Generated by Django 2.2.10 on 2020-02-28 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200225_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='stage',
            field=models.IntegerField(choices=[(0, 'Pre-season'), (1, 'First Games'), (2, 'Christmas'), (3, 'Central Games'), (4, 'Last Games'), (5, 'Post-season')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
